### PR TITLE
Added support for automatically setting of domain

### PR DESCRIPTION
**Pull request by jarl-dk**
Setting domain automatically based on Rack request environment.

### CODE REVIEW

**Comment by jarl-dk** [comment]
I must admit I am a bit new to Google Analytics...

Is this Pull Request pointless? Is the google analytics behaviour provided with this:

``` ruby
    config.middleware.use Rack::GoogleAnalytics,{
      :tracker => 'UA-12345-1',
      :async => true,
      :multiple => true,
    }
```

exactly the same as this:

``` ruby
    config.middleware.use Rack::GoogleAnalytics,{
      :tracker => 'UA-12345-1',
      :async => true,
    }
```

I ask, because if so, the pull request seem pointless

**Comment by kangguru** [comment]
As the default behavior of `setDomainName` is `auto` which will try to obtain the current host from `_setDomainName` this will be pretty much the same. Only thing is that you'll have to also set the `domain` config if you use the `multiple` option.

**Comment by jarl-dk** [comment]
So your point is when not having multiple domains, the default behaviour is automatic domain detection and setting. Setting the domain option is only necessary when `:multiple => true`.

If so, maybe some description of this in the README would help.

**Comment by kangguru** [comment]
Thats how i get it :) I've added a bit to the [README](https://github.com/leehambley/rack-google-analytics/commit/ae19a6794f6f8342ca2593d77a8cda1d0024dcbb)

**Pull request closed without merging**
