### PR TITLE
Support Display Advertising features

### PR DESCRIPTION
**Pull request by 2get**
Universal Analytics supported display advertising features.

see it: https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad

Usage

``` ruby
use Rack::GoogleAnalytics, :tracker => 'UA-xxxxx-x', :advertising => true
```

### CODE REVIEW

**Comment by masarakki** [comment]
+1

**Comment by kangguru** [comment]
cool. stuff! thx

i'll prepare a release later this day

**Comment by 2get** [comment]
Thank you !

**Comment by kangguru** [comment]
sry for the delay 1.1.0 is now released

**Pull request merged**
