### PR TITLE
Ensure the body is closed after iterating over it

### PR DESCRIPTION
**Pull request by rymai**
Hi,

I was getting many `(deadlock; recursive locking)` errors on my Heroku app in production environment and not in staging and couldn't find the origin until if found [this thread](https://github.com/rack/rack/issues/349) and then [this post](http://johnbintz.github.com/blog/2012/03/05/closing-given-body-in-rack-middleware/).

Then I compared the Rack middleware of the staging and production environments and found that the only Rack middleware that was present in production and not in staging was this one! And in fact, it appeared that you didn't close the body after iterating over it so I fixed this and since then I didn't get any new `(deadlock; recursive locking)` errors. :)

I've also improved the overall gem architecture:
- Usage of Bundler;
- Add development dependencies;
- Creation of `lib/rack-google-analytics.rb` so `:require => 'rack/google-analytics'` in the Gemfile is not needed anymore.

I hope you like these changes, otherwise feel free to ignore them and merge only the fix in the first commit.

Thanks!

### CODE REVIEW

**Comment by leehambley** [comment]
Rymal, thanks for the comprehensive fixes, I'll make a note to pull these and ship a new release to Rubygems soon! (A little busy starting my own company right now)

**Comment by rymai** [comment]
No problem, take your time!

Thanks very much! :)

**Comment by leehambley** [comment]
https://rubygems.org/gems/rack-google-analytics

**Comment by rymai** [comment]
Awesome, thanks very much!

**Comment by leehambley** [comment]
Thank you indeed for the patch @rymai !

**Pull request merged**
